import type { PageElement } from './page-builder/types';

export function generateNextJSProject(pages: Array<{ slug: string; name: string; content: string; isHome: boolean }>, envVars: Record<string, string>) {
  const files: Record<string, string> = {};

  // Generate package.json
  files['package.json'] = JSON.stringify({
    name: 'generated-store',
    version: '1.0.0',
    private: true,
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start',
    },
    dependencies: {
      next: '^16.1.6',
      react: '^19.2.3',
      'react-dom': '^19.2.3',
      stripe: '^17.5.0',
    },
    devDependencies: {
      '@types/node': '^20',
      '@types/react': '^19',
      '@types/react-dom': '^19',
      typescript: '^5',
    },
  }, null, 2);

  // Generate next.config.js
  files['next.config.js'] = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
`;

  // Generate tsconfig.json
  files['tsconfig.json'] = JSON.stringify({
    compilerOptions: {
      target: 'es5',
      lib: ['dom', 'dom.iterable', 'esnext'],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      forceConsistentCasingInFileNames: true,
      noEmit: true,
      esModuleInterop: true,
      module: 'esnext',
      moduleResolution: 'node',
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: 'preserve',
      incremental: true,
      paths: {
        '@/*': ['./*'],
      },
    },
    include: ['next-env.d.ts', '**/*.ts', '**/*.tsx'],
    exclude: ['node_modules'],
  }, null, 2);

  // Generate .env.local
  const envContent = Object.entries(envVars)
    .map(([key, value]) => `${key}=${value}`)
    .join('\n');
  files['.env.local'] = envContent;

  // Generate pages
  pages.forEach((page) => {
    const elements = JSON.parse(page.content).elements || [];
    const pageComponent = generatePageComponent(elements);
    
    if (page.isHome) {
      files['app/page.tsx'] = pageComponent;
    } else {
      files[`app/${page.slug}/page.tsx`] = pageComponent;
    }
  });

  // Generate layout
  files['app/layout.tsx'] = `import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'My Store',
  description: 'Generated by DeliStore',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`;

  // Generate Stripe checkout API route if Stripe keys exist
  if (envVars.STRIPE_SECRET_KEY) {
    files['app/api/checkout/route.ts'] = generateStripeCheckoutRoute();
  }

  // Generate PayPal checkout API route if PayPal keys exist
  if (envVars.PAYPAL_CLIENT_ID) {
    files['app/api/paypal-checkout/route.ts'] = generatePayPalCheckoutRoute();
  }

  return files;
}

function generatePageComponent(elements: PageElement[]): string {
  const jsx = elements.map(el => generateElementJSX(el, 0)).join('\n      ');
  
  return `export default function Page() {
  return (
    <div>
      ${jsx}
    </div>
  )
}
`;
}

function generateElementJSX(element: PageElement, indent: number): string {
  const indentation = '  '.repeat(indent);
  const styleStr = JSON.stringify(element.style);

  switch (element.type) {
    case 'container':
      const children = element.children?.map(child => generateElementJSX(child, indent + 1)).join('\n') || '';
      return `${indentation}<div style={${styleStr}}>
${children}
${indentation}</div>`;

    case 'heading':
      return `${indentation}<h1 style={${styleStr}}>${element.content.text}</h1>`;

    case 'text':
      return `${indentation}<p style={${styleStr}}>${element.content.text}</p>`;

    case 'button':
      return `${indentation}<button style={${styleStr}}>${element.content.text}</button>`;

    case 'image':
      return `${indentation}<img src="${element.content.src}" alt="${element.content.alt || ''}" style={${styleStr}} />`;

    case 'video':
      return `${indentation}<video src="${element.content.src}" controls style={${styleStr}} />`;

    case 'link':
      return `${indentation}<a href="${element.content.href}" target="${element.content.target}" style={${styleStr}}>${element.content.text}</a>`;

    case 'divider':
      return `${indentation}<hr style={${styleStr}} />`;

    case 'checkout':
      if (element.content.provider === 'stripe') {
        return `${indentation}<form action="/api/checkout" method="POST">
${indentation}  <button type="submit" style={${styleStr}}>${element.content.text}</button>
${indentation}</form>`;
      } else {
        return `${indentation}<form action="/api/paypal-checkout" method="POST">
${indentation}  <button type="submit" style={${styleStr}}>${element.content.text}</button>
${indentation}</form>`;
      }

    default:
      return `${indentation}<div style={${styleStr}}>Unknown element</div>`;
  }
}

function generateStripeCheckoutRoute(): string {
  return `import { NextResponse } from 'next/server';
import Stripe from 'stripe';

const stripe = new Stripe(process.env.STRIPE_SECRET_KEY!, {
  apiVersion: '2024-12-18.acacia',
});

export async function POST(req: Request) {
  try {
    const session = await stripe.checkout.sessions.create({
      payment_method_types: ['card'],
      line_items: [
        {
          price_data: {
            currency: 'usd',
            product_data: {
              name: 'Product',
            },
            unit_amount: 2000,
          },
          quantity: 1,
        },
      ],
      mode: 'payment',
      success_url: \`\${req.headers.get('origin')}/success\`,
      cancel_url: \`\${req.headers.get('origin')}/cancel\`,
    });

    return NextResponse.redirect(session.url!);
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
`;
}

function generatePayPalCheckoutRoute(): string {
  return `import { NextResponse } from 'next/server';

export async function POST(req: Request) {
  try {
    const auth = Buffer.from(
      \`\${process.env.PAYPAL_CLIENT_ID}:\${process.env.PAYPAL_CLIENT_SECRET}\`
    ).toString('base64');

    const response = await fetch(
      \`https://api-m.\${process.env.PAYPAL_MODE === 'live' ? 'paypal' : 'sandbox.paypal'}.com/v2/checkout/orders\`,
      {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: \`Basic \${auth}\`,
        },
        body: JSON.stringify({
          intent: 'CAPTURE',
          purchase_units: [
            {
              amount: {
                currency_code: 'USD',
                value: '20.00',
              },
            },
          ],
          application_context: {
            return_url: \`\${req.headers.get('origin')}/success\`,
            cancel_url: \`\${req.headers.get('origin')}/cancel\`,
          },
        }),
      }
    );

    const order = await response.json();
    const approvalUrl = order.links.find((link: any) => link.rel === 'approve').href;

    return NextResponse.redirect(approvalUrl);
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
`;
}
